[package]
name = "map_ldtk"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = "0.19.1"
bevy_ecs_ldtk = { version = "0.15", default-features = false, features = ["derive", "internal_levels"] }
bevy_ggrs = "0.22.0"

bevy_fixed = { path = "../bevy_fixed"}
map = { path = "../map"}
game = { path = "../game"}
content = { path = "../content"}
run = { path = "../run"}
combat = { path = "../combat"}
sim_core = { path = "../sim_core"}
utils = { path = "../utils"}
world = { path = "../world" }
items = { path = "../items" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19.0"

bevy-inspector-egui = { version = "0.37.0", optional = true }

[dev-dependencies]
ron = "0.12"

[features]
debug_ui = ["bevy-inspector-egui"]
render = ["map/render", "bevy_ecs_ldtk/render"]