[package]
name = "animation"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = "0.19.1"
bevy_ggrs = "0.22.0"
bevy_fixed = { path = "../bevy_fixed" }
utils = { path = "../utils" }

serde = { version = "1.0", features = ["derive"] }

bevy_common_assets = { version = "0.17", features = ["ron"] }